version: '3.8'

services:
  ubuntu-service:
    build: .
    container_name: my-dev01
    volumes:
      - ./shared_folder:/shared_folder
      - ubuntu-data:/root
    ports:
      - "8888:8888"
    stdin_open: true
    tty: true

volumes:
  ubuntu-data:
